version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019

before_build:
- git checkout master
- ps: .\prep_build.ps1 "$env:APPVEYOR_BUILD_VERSION"
- type ".\ThorusCommon.IO\Properties\Version.cs"

build_script:
- dotnet build ".\Thorus.sln"
  
after_build:
- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 6"
- ISCC /Q ".\Installer\Thorus.iss"
- 7z a thorus-setup.zip ".\output\*.*"

artifacts:
- path: thorus-setup.zip
  name: thorus-setup

deploy:
    provider: FTP
    protocol: ftp
    host: ocpa.ro
    username: ocparo_ftpops
    password: 
        secure: Vu0FvCIJ5sKkVuiZoWBhUA==
    folder: content/Meteo/current/
    application: thorus-setup
